{{- if eq (include "tempo.shouldDeployUpgradeResources" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.upgradeJob.role }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": {{ dig "hook" "phase" "pre-upgrade" .Values.upgradeJob }}
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": {{ dig "hook" "deletePolicy" "hook-succeeded,before-hook-creation" .Values.upgradeJob | quote }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "delete"]
{{- end }}