{{- if eq (include "tempo.shouldDeployUpgradeResources" .) "true" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.upgradeJob.roleBinding }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": {{ dig "hook" "phase" "pre-upgrade" .Values.upgradeJob }}
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": {{ dig "hook" "deletePolicy" "hook-succeeded,before-hook-creation" .Values.upgradeJob | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.upgradeJob.role }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.upgradeJob.serviceAccount }}
  namespace: {{ .Release.Namespace }}
{{- end }}