{{- if eq (include "tempo.shouldDeployUpgradeResources" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.upgradeJob.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": {{ dig "hook" "phase" "pre-upgrade" .Values.upgradeJob }}
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": {{ dig "hook" "deletePolicy" "hook-succeeded,before-hook-creation" .Values.upgradeJob | quote }}
{{- end }}